/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentQuizzesRouteImport } from './routes/student.quizzes'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as EmbedCodeRouteImport } from './routes/embed.$code'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardSessionsRouteImport } from './routes/_authenticated/dashboard.sessions'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardGuideRouteImport } from './routes/_authenticated/dashboard.guide'
import { Route as AuthenticatedTeacherQuizzesCreateRouteImport } from './routes/_authenticated/teacher.quizzes.create'
import { Route as AuthenticatedDashboardSessionIdRouteImport } from './routes/_authenticated/dashboard.session.$id'

const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentQuizzesRoute = StudentQuizzesRouteImport.update({
  id: '/student/quizzes',
  path: '/student/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCodeRoute = EmbedCodeRouteImport.update({
  id: '/embed/$code',
  path: '/embed/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSessionsRoute =
  AuthenticatedDashboardSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGuideRoute =
  AuthenticatedDashboardGuideRouteImport.update({
    id: '/guide',
    path: '/guide',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedTeacherQuizzesCreateRoute =
  AuthenticatedTeacherQuizzesCreateRouteImport.update({
    id: '/quizzes/create',
    path: '/quizzes/create',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedDashboardSessionIdRoute =
  AuthenticatedDashboardSessionIdRouteImport.update({
    id: '/session/$id',
    path: '/session/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/developer': typeof DeveloperRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/embed/$code': typeof EmbedCodeRoute
  '/join/$code': typeof JoinCodeRoute
  '/quiz/$id': typeof QuizIdRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/dashboard/guide': typeof AuthenticatedDashboardGuideRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/session/$id': typeof AuthenticatedDashboardSessionIdRoute
  '/teacher/quizzes/create': typeof AuthenticatedTeacherQuizzesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/developer': typeof DeveloperRoute
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/embed/$code': typeof EmbedCodeRoute
  '/join/$code': typeof JoinCodeRoute
  '/quiz/$id': typeof QuizIdRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/dashboard/guide': typeof AuthenticatedDashboardGuideRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/session/$id': typeof AuthenticatedDashboardSessionIdRoute
  '/teacher/quizzes/create': typeof AuthenticatedTeacherQuizzesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/developer': typeof DeveloperRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/embed/$code': typeof EmbedCodeRoute
  '/join/$code': typeof JoinCodeRoute
  '/quiz/$id': typeof QuizIdRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/_authenticated/dashboard/guide': typeof AuthenticatedDashboardGuideRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/session/$id': typeof AuthenticatedDashboardSessionIdRoute
  '/_authenticated/teacher/quizzes/create': typeof AuthenticatedTeacherQuizzesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/developer'
    | '/dashboard'
    | '/teacher'
    | '/embed/$code'
    | '/join/$code'
    | '/quiz/$id'
    | '/student/quizzes'
    | '/dashboard/guide'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/sessions'
    | '/dashboard/'
    | '/dashboard/session/$id'
    | '/teacher/quizzes/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/developer'
    | '/teacher'
    | '/embed/$code'
    | '/join/$code'
    | '/quiz/$id'
    | '/student/quizzes'
    | '/dashboard/guide'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/sessions'
    | '/dashboard'
    | '/dashboard/session/$id'
    | '/teacher/quizzes/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/developer'
    | '/_authenticated/dashboard'
    | '/_authenticated/teacher'
    | '/embed/$code'
    | '/join/$code'
    | '/quiz/$id'
    | '/student/quizzes'
    | '/_authenticated/dashboard/guide'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/sessions'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/session/$id'
    | '/_authenticated/teacher/quizzes/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DeveloperRoute: typeof DeveloperRoute
  EmbedCodeRoute: typeof EmbedCodeRoute
  JoinCodeRoute: typeof JoinCodeRoute
  QuizIdRoute: typeof QuizIdRoute
  StudentQuizzesRoute: typeof StudentQuizzesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/quizzes': {
      id: '/student/quizzes'
      path: '/student/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof StudentQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$code': {
      id: '/embed/$code'
      path: '/embed/$code'
      fullPath: '/embed/$code'
      preLoaderRoute: typeof EmbedCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sessions': {
      id: '/_authenticated/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof AuthenticatedDashboardSessionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/guide': {
      id: '/_authenticated/dashboard/guide'
      path: '/guide'
      fullPath: '/dashboard/guide'
      preLoaderRoute: typeof AuthenticatedDashboardGuideRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/teacher/quizzes/create': {
      id: '/_authenticated/teacher/quizzes/create'
      path: '/quizzes/create'
      fullPath: '/teacher/quizzes/create'
      preLoaderRoute: typeof AuthenticatedTeacherQuizzesCreateRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/dashboard/session/$id': {
      id: '/_authenticated/dashboard/session/$id'
      path: '/session/$id'
      fullPath: '/dashboard/session/$id'
      preLoaderRoute: typeof AuthenticatedDashboardSessionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardGuideRoute: typeof AuthenticatedDashboardGuideRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardSessionsRoute: typeof AuthenticatedDashboardSessionsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardSessionIdRoute: typeof AuthenticatedDashboardSessionIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardGuideRoute: AuthenticatedDashboardGuideRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardSessionsRoute: AuthenticatedDashboardSessionsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardSessionIdRoute: AuthenticatedDashboardSessionIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherQuizzesCreateRoute: typeof AuthenticatedTeacherQuizzesCreateRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherQuizzesCreateRoute:
    AuthenticatedTeacherQuizzesCreateRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DeveloperRoute: DeveloperRoute,
  EmbedCodeRoute: EmbedCodeRoute,
  JoinCodeRoute: JoinCodeRoute,
  QuizIdRoute: QuizIdRoute,
  StudentQuizzesRoute: StudentQuizzesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
