// This file is automatically generated. Do not edit it directly.
// Security note: Modified to use Firebase ID tokens via Supabase's accessToken
// callback instead of the insecure x-firebase-uid header (Phase 5 security fix).
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

// Strip any hidden Unicode/BOM characters that break HTTP headers (ISO-8859-1 only)
function sanitizeHeaderValue(value: string): string {
  // eslint-disable-next-line no-control-regex
  return value.replace(/[^\x00-\xFF]/g, '').trim();
}

// Custom fetch that ensures the apikey header is always present and
// header values are sanitized. The x-firebase-uid header has been REMOVED —
// identity is now established via a cryptographically verified Firebase JWT
// supplied through the accessToken callback below.
function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, sanitizeHeaderValue(value)));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs — strip if
    // the SDK accidentally set them as a bearer token.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', sanitizeHeaderValue(supabaseKey));

    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = sanitizeHeaderValue((import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL) ?? '');
  const SUPABASE_PUBLISHABLE_KEY = sanitizeHeaderValue((import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY) ?? '');

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    // accessToken supplies the Firebase ID token as the Authorization header on
    // every Supabase request. Supabase verifies it against Firebase's JWKS
    // (configured in Dashboard → Auth → Third-Party Auth) before trusting any
    // identity claim — closing the x-firebase-uid header spoofing vulnerability.
    accessToken: async () => {
      if (typeof window === 'undefined') return null; // SSR: no Firebase auth
      try {
        const { auth } = await import('@/lib/firebase');
        return (await auth.currentUser?.getIdToken()) ?? null;
      } catch (e) {
        console.warn('[Supabase] Failed to retrieve Firebase ID token:', e);
        return null;
      }
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
